Repository AxonIQ/axonserver-connector-java, pull requests merged in 2020-10, with the labels that each got.

#11 Added dependabot to the project
  .github/dependabot.yml
Labels: Priority 3: Could, Status: In Progress, Type: Dependency Upgrade

#24 Handle failure during subscription of query handlers.
  src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#27 Update gRPC and Netty TCNative to latest (compatible) versions
  pom.xml
Labels: Priority 1: Must, Status: In Progress, Type: Dependency Upgrade

#28 Ensure that error reading events for agggregate are propagated
  src/main/java/io/axoniq/axonserver/connector/event/AggregateEventStream.java
  src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
  src/test/java/io/axoniq/axonserver/connector/event/EventHandlingTest.java
  src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#30 Client reconnect when stream is completed unexpectedly by the server.
  src/main/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStream.java
  src/main/java/io/axoniq/axonserver/connector/impl/StreamUnexpectedlyCompletedException.java
  src/test/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStreamTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug
