Repository AxonIQ/axonserver-connector-java, pull requests merged in 2020-11, with the labels that each got.

#33 Fix subscribe when disconnected
  src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
  src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/command/CommandChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/command/CommandChannelTest.java
  src/test/java/io/axoniq/axonserver/connector/event/EventHandlingIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java
Labels: Priority 1: Must, Status: Resolved, Type: Bug

#34 Added automatic release notes on milestone closure
  .github/release-notes.yml
  .github/workflows/release-notes.yml
Labels: Priority 3: Could, Status: Resolved, Type: Enhancement

#35 Connector connection recovery improvement
  src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStream.java
  src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
  src/main/java/io/axoniq/axonserver/connector/impl/ContextConnection.java
  src/main/java/io/axoniq/axonserver/connector/impl/ControlChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
  src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStreamTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java
Labels: Priority 1: Must, Status: In Progress, Type: Bug

#42 Refactoring of instruction sending logic
  src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/control/ControlChannel.java
  src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/impl/AbstractAxonServerChannel.java
  src/main/java/io/axoniq/axonserver/connector/impl/ContextConnection.java
  src/main/java/io/axoniq/axonserver/connector/impl/ControlChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/impl/HeartbeatMonitor.java
  src/main/java/io/axoniq/axonserver/connector/impl/HeartbeatSender.java
  src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
  src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/HeartbeatMonitorTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement
