Repository AxonIQ/axonserver-connector-java, pull requests merged in 2021-06, with the labels that each got.

#76 Implemented ad-hoc query API for events
  src/main/java/io/axoniq/axonserver/connector/event/EventChannel.java
  src/main/java/io/axoniq/axonserver/connector/event/EventQueryResultEntry.java
  src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
  src/test/java/io/axoniq/axonserver/connector/event/EventHandlingIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/testutils/MessageFactory.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#77 Splitted builds into pr and not pr, added ghactions to dependabot and other minors
  .github/dependabot.yml
  .github/release-notes.yml
  .github/workflows/main.yml
  .github/workflows/pullrequest.yml
  .github/workflows/release-notes.yml
Labels: Priority 3: Could, Status: In Progress, Type: Enhancement

#81 Fix an issue with slow reconnection when server nodes shut down
  src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
Labels: Priority 1: Must, Type: Bug
