Repository AxonIQ/axonserver-connector-java, pull requests merged in 2021-02, with the labels that each got.

#53 Added grpc-level flow control to all streaming calls
  src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
  src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/impl/AssertUtils.java
  src/main/java/io/axoniq/axonserver/connector/impl/ControlChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/impl/FlowControlledStream.java
  src/main/java/io/axoniq/axonserver/connector/impl/SynchronizedRequestStream.java
  src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
  src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/BufferedStreamTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/FlowControlledBufferTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/FlowControlledStreamTest.java
  src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java
Labels: Priority 2: Should, Type: Enhancement

#55 Remove aggregate sequence validation
  src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStream.java
  src/test/java/io/axoniq/axonserver/connector/event/impl/BufferedAggregateEventStreamTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Enhancement

#56 Improved connection recovery when using proxies
  src/main/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannel.java
  src/main/java/io/axoniq/axonserver/connector/impl/ControlChannelImpl.java
  src/test/java/io/axoniq/axonserver/connector/command/CommandChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/AxonServerManagedChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/query/QueryChannelIntegrationTest.java
Labels: Priority 2: Should, Status: In Progress, Type: Bug
