Repository AxonIQ/axonserver-connector-java, pull requests merged in 2022-09, with the labels that each got.

#232 Dependency updates
  pom.xml
  src/main/java/io/axoniq/axonserver/connector/AxonServerConnectionFactory.java
Labels: Type: Dependency Upgrade, Status: In Progress, Priority 1: Must, CVSS: Medium

#231 Fix the subscriptionsCompleted boolean in query and command channels
  src/main/java/io/axoniq/axonserver/connector/command/impl/CommandChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/query/impl/QueryChannelImpl.java
Labels: Type: Bug, Status: In Progress, Priority 1: Must

#241 Upgrade Testcontainers dependency and replace OkHTTP3 for Apache HttpClient 5
  pom.xml
  src/test/java/io/axoniq/axonserver/connector/AbstractAxonServerIntegrationTest.java
  src/test/java/io/axoniq/axonserver/connector/impl/ControlChannelIntegrationTest.java
Labels: Type: Dependency Upgrade, Status: In Progress, Priority 2: Should

#225 Add clientId and componentName to events request
  src/main/java/io/axoniq/axonserver/connector/event/impl/BufferedEventStream.java
  src/main/java/io/axoniq/axonserver/connector/event/impl/EventChannelImpl.java
  src/main/java/io/axoniq/axonserver/connector/impl/AbstractIncomingInstructionStream.java
  src/main/java/io/axoniq/axonserver/connector/impl/FlowControlledStream.java
  src/main/java/io/axoniq/axonserver/connector/query/impl/SubscriptionQueryStream.java
  src/test/java/io/axoniq/axonserver/connector/command/CommandChannelIntegrationTest.java
Labels: Type: Enhancement, Status: In Progress, Priority 2: Should
